## import libraries

In [290]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## import dataset using pandas lib. and named it as dataset

In [262]:
dataset=pd.read_csv('DataSet.csv')

In [291]:
dataset

Developer   Age   Salary Married
0   Karachi  42.0  78000.0      No
1    Lahore  32.0  48000.0     Yes
2   Karachi  36.0  60000.0      No
3    Multan  41.0  68000.0      No
4    Lahore  42.0      NaN     Yes
5    Multan  43.0  59000.0     Yes
6   Karachi   NaN  59000.0      No
7    Lahore  44.0  79000.0     Yes
8    Multan  52.0  99000.0      No
9    Lahore  32.0  69000.0     Yes

## extracting all col except last and set it as X variable

In [264]:
X=dataset.iloc[:,:-1].values

In [265]:
X

array([['Karachi', 42.0, 78000.0],
       ['Lahore', 32.0, 48000.0],
       ['Karachi', 36.0, 60000.0],
       ['Multan', 41.0, 68000.0],
       ['Lahore', 42.0, nan],
       ['Multan', 43.0, 59000.0],
       ['Karachi', nan, 59000.0],
       ['Lahore', 44.0, 79000.0],
       ['Multan', 52.0, 99000.0],
       ['Lahore', 32.0, 69000.0]], dtype=object)

## set last col. by Y

In [292]:
Y=dataset.iloc[:,3].values

In [293]:
Y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

## Using SimpleImputer class for putting values where nan either mean , meadia or most frequent

In [268]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='mean')
imputer=imputer.fit(X[:,1:3])
X[:,1:3]=imputer.transform(X[:,1:3])

In [269]:
X

array([['Karachi', 42.0, 78000.0],
       ['Lahore', 32.0, 48000.0],
       ['Karachi', 36.0, 60000.0],
       ['Multan', 41.0, 68000.0],
       ['Lahore', 42.0, 68777.77777777778],
       ['Multan', 43.0, 59000.0],
       ['Karachi', 40.44444444444444, 59000.0],
       ['Lahore', 44.0, 79000.0],
       ['Multan', 52.0, 99000.0],
       ['Lahore', 32.0, 69000.0]], dtype=object)

In [270]:
XX=dataset.iloc[:,:-1].values

In [271]:
XX

array([['Karachi', 42.0, 78000.0],
       ['Lahore', 32.0, 48000.0],
       ['Karachi', 36.0, 60000.0],
       ['Multan', 41.0, 68000.0],
       ['Lahore', 42.0, nan],
       ['Multan', 43.0, 59000.0],
       ['Karachi', nan, 59000.0],
       ['Lahore', 44.0, 79000.0],
       ['Multan', 52.0, 99000.0],
       ['Lahore', 32.0, 69000.0]], dtype=object)

In [272]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='median')
imputer=imputer.fit(XX[:,1:3])
XX[:,1:3]=imputer.transform(XX[:,1:3])

In [273]:
XX

array([['Karachi', 42.0, 78000.0],
       ['Lahore', 32.0, 48000.0],
       ['Karachi', 36.0, 60000.0],
       ['Multan', 41.0, 68000.0],
       ['Lahore', 42.0, 68000.0],
       ['Multan', 43.0, 59000.0],
       ['Karachi', 42.0, 59000.0],
       ['Lahore', 44.0, 79000.0],
       ['Multan', 52.0, 99000.0],
       ['Lahore', 32.0, 69000.0]], dtype=object)

In [274]:
XXX=dataset.iloc[:,:-1].values

In [275]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='most_frequent')
imputer=imputer.fit(XXX[:,1:3])
XXX[:,1:3]=imputer.transform(XXX[:,1:3])

In [276]:
XXX

array([['Karachi', 42.0, 78000.0],
       ['Lahore', 32.0, 48000.0],
       ['Karachi', 36.0, 60000.0],
       ['Multan', 41.0, 68000.0],
       ['Lahore', 42.0, 59000.0],
       ['Multan', 43.0, 59000.0],
       ['Karachi', 32.0, 59000.0],
       ['Lahore', 44.0, 79000.0],
       ['Multan', 52.0, 99000.0],
       ['Lahore', 32.0, 69000.0]], dtype=object)

## labelling developer address string into integer 

In [277]:
from sklearn.preprocessing import LabelEncoder

In [278]:
labelencoder_X=LabelEncoder()
X[:,0]=labelencoder_X.fit_transform(X[:,0])

In [279]:
X

array([[0, 42.0, 78000.0],
       [1, 32.0, 48000.0],
       [0, 36.0, 60000.0],
       [2, 41.0, 68000.0],
       [1, 42.0, 68777.77777777778],
       [2, 43.0, 59000.0],
       [0, 40.44444444444444, 59000.0],
       [1, 44.0, 79000.0],
       [2, 52.0, 99000.0],
       [1, 32.0, 69000.0]], dtype=object)

## breaking the labels into three col where each location will be inserted with 1 and other with 0

In [280]:
from sklearn.preprocessing import OneHotEncoder

In [281]:
onehotencoder=OneHotEncoder(categories='auto',sparse=True)


In [282]:
X=onehotencoder.fit_transform(X).toarray()

In [283]:
X

array([[1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 1., 0., 0.],
       [0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 1.],
       [0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 0.]])

## splitting the dataset using train_test_split method

In [284]:
from sklearn.model_selection import train_test_split

In [285]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=0)

## standarizing the dataset in between 0 and 1

In [286]:
from sklearn.preprocessing import StandardScaler 
sc_X=StandardScaler()

In [287]:
X_test=sc_X.fit_transform(X_test)
X_train=sc_X.fit_transform(X_train)

In [288]:
X_test

array([[ 1.,  0., -1.,  0.,  1.,  0.,  0.,  0.,  0.,  0., -1.,  0.,  0.,
         1.,  0.,  0.,  0.,  0.,  0., -1.],
       [-1.,  0.,  1.,  0., -1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,
        -1.,  0.,  0.,  0.,  0.,  0.,  1.]])

In [289]:
X_train

array([[-0.57735027,  1.        , -0.57735027, -0.57735027,  0.        ,
        -0.37796447, -0.37796447,  1.73205081, -0.37796447, -0.37796447,
         0.        , -0.37796447, -0.57735027,  0.        , -0.37796447,
         2.64575131, -0.37796447, -0.37796447, -0.37796447,  0.        ],
       [-0.57735027,  1.        , -0.57735027,  1.73205081,  0.        ,
        -0.37796447, -0.37796447, -0.57735027, -0.37796447, -0.37796447,
         0.        , -0.37796447, -0.57735027,  0.        , -0.37796447,
        -0.37796447,  2.64575131, -0.37796447, -0.37796447,  0.        ],
       [-0.57735027,  1.        , -0.57735027,  1.73205081,  0.        ,
        -0.37796447, -0.37796447, -0.57735027, -0.37796447, -0.37796447,
         0.        ,  2.64575131, -0.57735027,  0.        , -0.37796447,
        -0.37796447, -0.37796447, -0.37796447, -0.37796447,  0.        ],
       [ 1.73205081, -1.        , -0.57735027, -0.57735027,  0.        ,
         2.64575131, -0.37796447, -0.57735027, -

## The End